### ISSUE TITLE
Wiki

### ISSUE THREAD

**Issue by shaihi** [robotican/armadillo2#3]
Not sure this is the place for this...
[Arm manipulation tutorial](http://wiki.ros.org/armadillo2/Tutorials/Arm%20manipulation) - the roslaunch command is outdated

**Comment by elhayra** [comment]
> Not sure this is the place for this...
This is the right place for issues with our documentation as well. 

> Arm manipulation tutorial - the roslaunch command is outdated
We updated the command. Thank you
