### ISSUE TITLE
Softkinetic crashes when run with Kinect on robot

### ISSUE THREAD

**Issue by shaihi** [robotican/armadillo2#4]
### Issue Description
Launching the robot with both cameras results in only head camera working. Each seperately works fine.
Tryingot launch the softkinetic after main launch results in same behaviour
### Steps To Reproduce The Behavior
roslaunch armadillo2 armadillo2.launch lidar:=false kinect:=true moveit:=false softkinetic:=true
### Relavent Log Files And Pictures
 Register pulse input [4] to: left_wheel_joint
[softkinetic-8] process has died [pid 3001, exit code -6, cmd /home/armadillo2/catkin_ws/devel/lib/softkinetic_camera/softkinetic_bringup_node 0 __name:=softkinetic __log:=/home/armadillo2/.ros/log/705a19a8-2771-11e8-8b1a-14b31f2d22c5/softkinetic-8.log].
log file: /home/armadillo2/.ros/log/705a19a8-2771-11e8-8b1a-14b31f2d22c5/softkinetic-8*.log
[Info] [Freenect2DeviceImpl] stopped

**Comment by shaihi** [comment]
Running it in reverse order (Softkinetic and then Kinect2) works

**Comment by shaihi** [comment]
Did you fix the armadillo2.launch file? so it will be in the correct load order automatically?

**Comment by elhayra** [comment]
In ROS one can't control the order of which nodes are loaded from a launch file. If you wish you can write a script that runs softkinetic launch, delay for couple of seconds and then launch armadillo2 main launch
